### ISSUE TITLE
Dockerize it

### ISSUE THREAD

**Issue by Kippenhof** [Scoder12/murdermystery#215]
It would be nice, if you could provide an Dockerized version, for easy deployment on many servers.

**Comment by Scoder12** [comment]
It is pretty easy to deploy I'd say, just grab the latest release from the releases page and it should run in any linux environment. A Dockerfile would probably just be an alpine image that copies the binary in. I could write a Dockerfile to build from source if that would be helpful to you.

**Comment by Kippenhof** [comment]
> It is pretty easy to deploy I'd say, just grab the latest release from the releases page and it should run in any linux environment. A Dockerfile would probably just be an alpine image that copies the binary in. I could write a Dockerfile to build from source if that would be helpful to you. 

Hi, thx for the Answer,

Thanks for the Tipps, you made it sound not that complicated, so I maybe try it myself. If I get no further, and you still willing to help, I would open the Issue again. :)
